"""Initial schema for 9 entities

Revision ID: 7a00a2c7bd94
Revises: 
Create Date: 2026-09-30 23:06:10.922804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a00a2c7bd94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intents',
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('role_pack', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('intent_type', sa.String(), nullable=False),
    sa.Column('needs_retrain', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("intent_type IN ('dynamic_workflow', 'static_faq')", name='chk_intent_type'),
    sa.CheckConstraint("role_pack IN ('hr', 'it', 'admissions')", name='chk_intent_role_pack'),
    sa.PrimaryKeyConstraint('intent_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('response_templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('role_pack', sa.String(), nullable=False),
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('base_text', sa.String(), nullable=False),
    sa.Column('allow_rephrasing', sa.Boolean(), nullable=True),
    sa.Column('available_variables', sa.JSON().with_variant(postgresql.ARRAY(sa.String()), 'postgresql'), nullable=True),
    sa.CheckConstraint("role_pack IN ('hr', 'it', 'admissions')", name='chk_response_template_role_pack'),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('template_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_pack', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role_pack IN ('hr', 'it', 'admissions')", name='chk_conversation_role_pack'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('response_variants',
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('variant_text', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['response_templates.template_id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_table('training_phrases',
    sa.Column('phrase_id', sa.String(), nullable=False),
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('phrase_text', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.intent_id'], ),
    sa.PrimaryKeyConstraint('phrase_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('intent_name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("sender IN ('user', 'bot')", name='chk_message_sender'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('current_form', sa.String(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('slots', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('messages')
    op.drop_table('training_phrases')
    op.drop_table('response_variants')
    op.drop_table('conversations')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('response_templates')
    op.drop_table('intents')
    # ### end Alembic commands ###
